 # docker-compose.yaml
  version: '3.3'
  services:
    jenkins:
      image: jenkins/jenkins:jdk11
      privileged: true
      user: root
      ports:
       - 8081:8080
       - 50000:50000
      container_name: jenkins
      volumes:
        - ~/jenkins:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock

    docker:
      image: docker:dind
      container_name: docker
      privileged: true
      networks:
        devops:
          ipv4_address:
      volumes:
      - /var/lib/docker
    restart: always
    environment:
      - SONARQUBE_HOST=http://sonarqube:9000

    nexus:
      image: sonatype/nexus3
      container_name: nexus
      user: root
      ports:
        - 8088:8081
        - 8085:8085
      volumes:
        - /home/nexus:/nexus-data
      restart: always

    sonarqube:
         image: sonarqube:community
         container_name: sonarqube
         depends_on:
           - db
         environment:
           SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
           SONAR_JDBC_USERNAME: sonar
           SONAR_JDBC_PASSWORD: sonar
         volumes:
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_extensions:/opt/sonarqube/extensions
            - sonarqube_logs:/opt/sonarqube/logs
         ports:
            - "9000:9000"

    db:
        image: postgres:13
        container_name: postgresql
        environment:
          POSTGRES_USER: sonar
          POSTGRES_PASSWORD: sonar
          POSTGRES_DB: sonar
        volumes:
           - postgresql:/var/lib/postgresql
           - postgresql_data:/var/lib/postgresql/data

  volumes:
    jenkins-data: {}
    jenkins-home: {}
    sonarqube_data:
    sonarqube_extensions:
    sonarqube_logs:
    postgresql:
    postgresql_data: